version: '3.8'

services:
  transfer-microservice:
    container_name: transfer-microservice
    build: /home/seu-usuario/corebankingmicroservices-cleanarch/transfer-microservice/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__RabbitMQHost=rabbitmq
      - ConnectionStrings__RedisHost=redis-cache
      - ConnectionStrings__MongoDb=mongodb://mongo-db:27018/TransferDb
    dns:
      - 8.8.8.8
    ports:
      - "5000:80" # Expor a porta 5000
    networks:
      - microservice-network
    depends_on:
      - mongo-db
      - redis-cache
      - rabbitmq
    command: ["dotnet", "/app/TransferMicroservice.dll"]

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: TransferDb
    ports:
      - "27018:27017"
    volumes:
      - ./databases/mongo/data:/data/db
    networks:
      - microservice-network

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6380:6379"
    networks:
      - microservice-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5674:5672"
      - "15674:15672"
    networks:
      - microservice-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - microservice-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3018:3000"
    networks:
      - microservice-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
